<?php
	/**
	* @file
	* A block module that displays recent blog and forum posts.
	*/
	function nijo_help($path, $arg) {
		switch ($path) {
		  case "admin/help#nijo":
		    return '<p>'.  t("Displays links to nodes created on this date") .'</p>';
		    break;
		}
	}
	function nijo_block_info() {
		$blocks['nijo'] = array(
		  'info' => t('Nijo'), //The name that will appear in the block list.
		  'cache' => DRUPAL_CACHE_PER_ROLE //Default
		);
		return $blocks;
	}
	function nijo_contents() {
		//Get today's date.
		$today = getdate();
		//Calculate midnight a week ago.
		$start_time = mktime(0, 0, 0,$today['mon'],($today['mday'] - 14), $today['year']);
		//Get all posts from one week ago to the present.
		$end_time = time();

		//NEW LINE 
		$max_num = variable_get('nijo_max', 3);

		//Use Database API to retrieve current posts.
		$query = db_select('node', 'n')
		  ->fields('n', array('nid', 'title', 'created'))
		  ->condition('status', 1) //Published.
		  ->condition('created', array($start_time, $end_time), 'BETWEEN')
		  ->orderBy('created', 'DESC') //Most recent first.
		  ->range(0, $max_num) //NEW LINE
		  ->execute();

		return $query;
	}
	function nijo_block_view($delta = '') {
		switch($delta){
		  case 'nijo':
		    $block['subject'] = t('Nijo');
		    if(user_access('access content')){
		      //Use our custom function to retrieve data.
		      $result = nijo_contents();
		      //Array to contain items for the block to render.
		      $items = array();
		      //Iterate over the resultset and format as links.
		      foreach ($result as $node){
		        $items[] = array(
		          'data' => l($node->title, 'node/' . $node->nid),
		        ); 
		      }
		    
		      if (empty($items)) { //No content in the last week.
		        $block['content'] = t('No posts available.');  
		      } 
		      else {
		        //Pass data through theme function.
		        $block['content'] = theme('item_list', array(
		          'items' => $items));
		      }
		    }
		}
		return $block;
	}
	function nijo_menu() {
		$items = array();

		$items['admin/structure/block/manage/nijo/nijo/configure'] = array(
		  'title' => 'Nijo',
		  'description' => 'Configuration for Nijos module',
		  'page callback' => 'drupal_get_form',
		  'page arguments' => array('nijo_form'),
		  'access arguments' => array('access administration pages'),
		  'type' => MENU_NORMAL_ITEM,
		);
		$items['nijo'] = array(
				'title' => 'Nijo',
				'page callback' => '_nijo_page',
				'access arguments' => array('access nijo content'),
				'type' => MENU_NORMAL_ITEM, //Will appear in Navigation menu.
		);
		return $items;
	}
	function nijo_form($form, &$form_state) {
		$form['nijo_max'] = array(
		  '#type' => 'textfield',
		  '#title' => t('Maximum number of posts'),
		  '#default_value' => variable_get('nijo_max', 3),
		  '#size' => 2,
		  '#maxlength' => 2,
		  '#description' => t('The maximum number of links to display in the block.'),
		  '#required' => TRUE,
		);

		return system_settings_form($form);
	}
	function nijo_form_validate($form, &$form_state){
		$max_num = $form_state['values']['nijo_max'];
		if (!ctype_digit($max_num)){
		  form_set_error('nijo_max', t('You must enter a number for the maximum number of posts to display.'));
		} 
	}
	function nijo_permission(){
		return array(
		  'access nijo content' => array(
		    'title' => t('Access content for the Nijos module'),
		  )  
		);  
	}

